name: complaints_m

services:
  complaints-backend:
    build: .
    container_name: complaints-backend-m
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3018:3018"
    volumes:
      - ./backups:/app/backups
    networks:
      - proxy
      - n8n_default

networks:
  proxy:
    external: true
  n8n_default:
    external: true
